# Generated by Django 5.2.5 on 2025-09-01 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_recognition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for category', max_length=7)),
                ('icon', models.CharField(default='fas fa-utensils', help_text='FontAwesome icon class', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Food Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='nutritional_info',
            field=models.TextField(blank=True, help_text='Calories, protein, etc.'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='preparation_time',
            field=models.IntegerField(blank=True, help_text='Time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='pricing_unit',
            field=models.CharField(choices=[('item', 'Per Item'), ('gram', 'Per Gram'), ('portion', 'Per Portion'), ('serving', 'Per Serving')], default='item', max_length=20),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food_recognition.foodcategory'),
        ),
    ]
