# Generated by Django 5.2.5 on 2025-09-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_recognition', '0002_foodcategory_alter_menuitem_options_menuitem_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='nutritional_info',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='preparation_time',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='pricing_unit',
            field=models.CharField(choices=[('item', 'Per Item'), ('serving', 'Per Serving')], default='item', max_length=20),
        ),
    ]
