# Generated by Django 5.2.5 on 2025-09-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_recognition', '0003_remove_menuitem_nutritional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detecteditem',
            name='estimated_grams',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='detecteditem',
            name='quantity',
            field=models.FloatField(default=1.0),
        ),
    ]
