# Generated by Django 5.2.5 on 2025-09-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_recognition', '0004_detecteditem_estimated_grams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detecteditem',
            name='calculated_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
